"use client";
import {useEffect,useRef,useState} from 'react';
import {BookOpen,CalendarDays,Heart,House,Users,Sparkles,ArrowRight,ArrowLeft,Clock,Plus,Search,Check,ChevronRight,MessageCircle,ShieldCheck,Lightbulb,HandHeart,Leaf,X,Pencil,Trash2,RefreshCw} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';

import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Pagination} from '@/components/ui/pagination';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {lessons,categories,stages,vnDate,type Lesson} from '@/lib/lessons';
import {type Family,type Child,type LearningRecord} from '@/lib/family';
import {learningPath} from '@/lib/learning-path';

type View='today'|'library'|'schedule'|'journey'|'family';
const navigation=[{id:'today',title:'Học ngay',icon:House},{id:'library',title:'Thư viện bài học',icon:BookOpen},{id:'schedule',title:'Lộ trình',icon:CalendarDays},{id:'journey',title:'Hành trình',icon:Heart},{id:'family',title:'Gia đình',icon:Users}] as const;
const categoryIcons:Record<string,typeof Heart>={'Giao tiếp':MessageCircle,'Cảm xúc':Heart,'Tự lập':Leaf,'Tình bạn':HandHeart,'An toàn':ShieldCheck,'Trách nhiệm':Lightbulb};
const statusText={learned:'Đã cùng học',practice:'Đã thực hành',again:'Cần luyện thêm'};

function Choice({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue>{items.find(i=>i.value===value)?.label}</SelectValue></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
function Navigation({view,onNavigate}:{view:View;onNavigate:(v:View)=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenu>{navigation.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>{onNavigate(n.id);setOpenMobile(false)}}><n.icon/>{n.title}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>}
function LessonCard({lesson,onOpen,done=false}:{lesson:Lesson;onOpen:()=>void;done?:boolean}){const Icon=categoryIcons[lesson.category];return <button className="lesson-card" onClick={onOpen}><div className="card-top"><span className={'category-icon tone-'+categories.indexOf(lesson.category)}><Icon size={23}/></span><span className="lesson-number">{done?<Check size={18}/>:String(lesson.id).padStart(2,'0')}</span></div><span className="category-label">{lesson.category}</span><h3>{lesson.title}</h3><p>{lesson.goal}</p><div className="card-bottom"><span><Clock size={14}/> {lesson.minutes} phút</span><ChevronRight size={18}/></div></button>}
const headings:Record<View,[string,string]>={today:['Mở app, cùng con học điều hay.','365 bài kỹ năng sống cho trẻ tiểu học dưới 12 tuổi. Học lúc gia đình sẵn sàng.'],library:['Điều hay để dạy con mỗi ngày.','365 bài học dùng chung cho trẻ tiểu học dưới 12 tuổi, có hướng dẫn và thực hành.'],schedule:['Một năm, 365 điều hay.','12 chặng gợi ý. Tất cả bài học đều mở, có thể chọn và học lại bất cứ lúc nào.'],journey:['Những bước nhỏ đáng nhớ.','Ghi nhận điều con đã thử, theo nhịp của riêng con.'],family:['Gia đình, nơi con bắt đầu.','Dùng biệt danh để tạo không gian học cho từng con.']};
export default function FamilyApp(){
const [view,setView]=useState<View>('today');const [family,setFamily]=useState<Family|null>(null);const revision=useRef(0);const current=useRef<Family|null>(null);const lock=useRef(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [now]=useState(()=>new Date());
const [page,setPage]=useState(1);const [segment,setSegment]=useState('0');const [query,setQuery]=useState('');const [category,setCategory]=useState('Tất cả');const [filterChild,setFilterChild]=useState('all');
const [preview,setPreview]=useState<Lesson|null>(null);const [active,setActive]=useState<Lesson|null>(null);const [step,setStep]=useState(0);const [simple,setSimple]=useState(false);const [example,setExample]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [outcomes,setOutcomes]=useState<Record<string,{status:LearningRecord['status'];note:string}>>({});const [completed,setCompleted]=useState<Lesson|null>(null);const [resume,setResume]=useState<{id:number;step:number}|null>(null);
const [childDialog,setChildDialog]=useState(false);const [editChild,setEditChild]=useState<Child|null>(null);const [childName,setChildName]=useState('');const [deleteChild,setDeleteChild]=useState<Child|null>(null);
async function load(){setLoading(true);setError('');try{const r=await fetch('/api/family');const d=await r.json() as {family:Family;revision:number;error?:string};if(!r.ok)throw new Error(d.error);current.current=d.family;setFamily(d.family);revision.current=d.revision}catch(e){setError(e instanceof Error?e.message:'Không tải được dữ liệu.')}finally{setLoading(false)}}
async function save(next:Family){if(lock.current)return false;lock.current=true;setSaving(true);try{const r=await fetch('/api/family',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({family:next,revision:revision.current})});const d=await r.json() as {family:Family;revision:number;error?:string};if(!r.ok)throw new Error(d.error);current.current=d.family;setFamily(d.family);revision.current=d.revision;setError('');return true}catch(e){const message=e instanceof Error?e.message:'Chưa lưu được. Hãy thử lại.';toast.error(message);setError(message);return false}finally{lock.current=false;setSaving(false)}}
useEffect(()=>{void load();try{const r=JSON.parse(localStorage.getItem('cung-con-draft')||'null');if(r&&Number.isInteger(r.id)&&r.id>=1&&r.id<=lessons.length&&Number.isInteger(r.step)&&r.step>=0&&r.step<6)setResume(r)}catch{}},[]);
const scopeRecords=family?.records.filter(r=>filterChild==='all'||r.childId===filterChild)||[];
const path=learningPath(lessons,scopeRecords);const {learnedIds,total}=path;const todayLesson=family?path.next:null;const practices=scopeRecords.filter(r=>r.status==='practice').length;
const scopeLabel=filterChild==='all'?'Gia đình':family?.children.find(c=>c.id===filterChild)?.name||'Gia đình';
function go(v:View){setView(v);window.scrollTo({top:0,behavior:'smooth'})}
function start(lesson:Lesson,at=0,childId?:string){setCompleted(null);setPreview(null);setActive(lesson);setStep(at);setSimple(false);setExample(false);const f=current.current;const learner=childId||(filterChild!=='all'?filterChild:undefined);setSelected(learner?[learner]:(f?.children.map(c=>c.id)||[]));setOutcomes(Object.fromEntries((f?.children||[]).map(c=>{const r=f?.records.find(r=>r.childId===c.id&&r.lessonId===lesson.id);return[c.id,{status:r?.status||'learned',note:r?.note||''}]})));try{localStorage.setItem('cung-con-draft',JSON.stringify({id:lesson.id,step:at}))}catch{}setResume({id:lesson.id,step:at});window.scrollTo(0,0)}
function changeStep(n:number){setStep(n);setSimple(false);setExample(false);if(active){setResume({id:active.id,step:n});try{localStorage.setItem('cung-con-draft',JSON.stringify({id:active.id,step:n}))}catch{}}window.scrollTo(0,0)}
async function finish(){if(!family||!active)return;if(!selected.length){toast.error('Chọn ít nhất một con để ghi nhận.');return}const records=family.records.filter(r=>!(r.lessonId===active.id&&selected.includes(r.childId)));selected.forEach(id=>records.push({lessonId:active.id,childId:id,status:outcomes[id]?.status||'learned',note:outcomes[id]?.note||'',date:vnDate()}));if(await save({...family,records})){try{localStorage.removeItem('cung-con-draft')}catch{}setResume(null);setCompleted(active);setFilterChild(selected.length===1?selected[0]:'all');setActive(null);setView('today');window.scrollTo(0,0);toast.success('Đã lưu buổi học của gia đình.')}}
function openChild(child?:Child){setEditChild(child||null);setChildName(child?.name||'');setChildDialog(true)}
async function submitChild(e:React.FormEvent){e.preventDefault();if(!family)return;const name=childName.trim();if(!name)return;const child={id:editChild?.id||crypto.randomUUID(),name};const children=editChild?family.children.map(c=>c.id===child.id?child:c):[...family.children,child];if(await save({...family,children})){setChildDialog(false);if(active){setSelected(s=>[...new Set([...s,child.id])]);setOutcomes(o=>({...o,[child.id]:{status:'learned',note:''}}))}toast.success(editChild?'Đã cập nhật hồ sơ.':'Đã thêm con vào gia đình.')}}
async function removeChild(){if(!family||!deleteChild)return;const id=deleteChild.id;if(await save({...family,children:family.children.filter(c=>c.id!==id),records:family.records.filter(r=>r.childId!==id)})){setDeleteChild(null);setFilterChild('all');toast.success('Đã xóa hồ sơ và ghi nhận của con.')}}
const fold=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase();
const filtered=lessons.filter(l=>(category==='Tất cả'||l.category===category)&&fold(l.title+' '+l.goal+' '+l.story).includes(fold(query.trim())));
const pages=Math.max(1,Math.ceil(filtered.length/18));const visiblePage=Math.min(page,pages);
const segments=[0,31,59,90,120,151,181,212,243,273,304,334,365];
const startRef=useRef(start);startRef.current=start;
useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_parent_lesson',title:'Mở bài hướng dẫn cha mẹ',description:'Mở bài học ở bước chuẩn bị. Không đánh dấu hoàn thành và không ghi dữ liệu học tập.',inputSchema:{type:'object',properties:{lessonId:{type:'integer',minimum:1,maximum:365}},required:['lessonId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){const id=(input as {lessonId?:number})?.lessonId;if(!Number.isInteger(id)||!id||id<1||id>lessons.length)throw new Error('lessonId phải từ 1 đến 365');startRef.current(lessons[id-1]);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return{lessonId:id,stage:'Chuẩn bị',completed:false}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);

return <SidebarProvider><Sidebar><SidebarHeader><div className="brand"><span className="brand-mark"><BookOpen size={23}/></span><div>Cùng con<small>MỖI NGÀY MỘT ĐIỀU HAY</small></div></div></SidebarHeader><SidebarContent><p className="nav-label">KHÔNG GIAN GIA ĐÌNH</p><Navigation view={view} onNavigate={v=>{setActive(null);go(v)}}/></SidebarContent><SidebarFooter><div className="sidebar-note"><Heart size={22}/><p>Điều nhỏ mỗi ngày.<br/><strong>Gắn kết dài lâu.</strong></p></div><button className="account" onClick={()=>{setActive(null);go('family')}}><span>GĐ</span><div>Gia đình của bạn<small>Không gian riêng tư</small></div></button></SidebarFooter></Sidebar><main className="workspace"><header className="topbar"><div className="flex items-center gap-3"><SidebarTrigger/><span>Góc đồng hành của cha mẹ</span></div><span className="top-meta"><BookOpen size={17}/> Tiểu học · Học bất cứ lúc nào</span></header><div className="page-content">
{error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={load}><RefreshCw size={16}/> Tải lại dữ liệu</button></div>}
{active?<><button className="text-button back" onClick={()=>setActive(null)}><ArrowLeft size={16}/> Về không gian gia đình</button><div className="reader-heading"><div><p className="eyebrow">BÀI {String(active.id).padStart(2,'0')} · {active.category.toUpperCase()}</p><h1>{active.title}</h1></div><span className="reader-audience">Tiểu học · Dưới 12 tuổi</span></div><div className="reader-layout"><aside className="reader-index">{stages.map((s,i)=><button key={s} className={step===i?'selected':''} onClick={()=>changeStep(i)}><span>{i<step?<Check size={14}/>:i+1}</span>{s}</button>)}<p><Clock size={16}/> Khoảng {active.minutes} phút<br/>Có thể dừng và tiếp tục sau.</p></aside><section className="reader-main"><div className="reader-progress"><span>BƯỚC {step+1} / 6</span><Progress value={(step+1)/6*100} aria-label="Tiến độ hướng dẫn"/></div><h2>{stages[step]}</h2>
{step===0&&<><div className="goal-box"><Lightbulb size={22}/><div><strong>Sau buổi học hôm nay</strong><p>{active.goal}</p></div></div><h3>Trước khi gọi con cùng học</h3><p>Đọc lướt câu chuyện và hoạt động. Chọn một chỗ yên tĩnh, có thể ngồi ngang tầm với con. {active.id===1?'Chuẩn bị một chiếc hộp để đóng vai.':'Chuẩn bị giấy, bút hoặc đồ dùng an toàn nếu hoạt động cần.'}</p><div className="parent-tip"><span>CÙNG CON HỌC THEO CÁCH DỄ HIỂU</span><p>Dùng câu ngắn và ví dụ quen thuộc. Để con suy nghĩ, nói hoặc vẽ câu trả lời, rồi cùng làm mẫu nếu cần. Khi con đã hiểu, hỏi thêm vì sao con chọn cách đó. Có thể nghỉ và học lại theo nhịp của con.</p></div><h3>Lời mở đầu với con</h3><blockquote>“Hôm nay mình cùng học một điều nhỏ nhé. Bố/mẹ sẽ kể một câu chuyện, rồi mình cùng nghĩ và thử làm. Không cần trả lời thật nhanh đâu con.”</blockquote></>}
{step===1&&<><span className="content-label">CHA MẸ KỂ CHO CON</span><blockquote className="story">{active.story}</blockquote><div className="parent-tip"><span>DỪNG MỘT NHỊP</span><p>Kể chậm, dùng tên nhân vật. Nếu con muốn kể chuyện tương tự của mình, hãy lắng nghe trước khi chuyển bước.</p></div></>}
{step===2&&<><span className="content-label">HỎI VÀ LẮNG NGHE CON</span><blockquote>{active.question}</blockquote><h3>Nếu con chưa biết trả lời</h3><p>“Con nghĩ nhân vật đang cần điều gì? Mình có thể nhờ ai hoặc thử làm gì trước?”</p><div className="parent-tip"><span>KHÔNG CẦN MỘT ĐÁP ÁN DUY NHẤT</span><p>Chờ con suy nghĩ. Hỏi “Vì sao con nghĩ như vậy?” và ghi nhận ý tưởng trước khi bổ sung cách phù hợp.</p></div></>}
{step===3&&<><span className="content-label">LỜI GIẢI THÍCH CHO CON</span><blockquote>{active.explain}</blockquote><div className="flex flex-wrap gap-3"><button className="button secondary" aria-expanded={simple} onClick={()=>setSimple(!simple)}><Lightbulb size={16}/> Con chưa hiểu</button><button className="button secondary" aria-expanded={example} onClick={()=>setExample(!example)}><MessageCircle size={16}/> Thử thêm cách nói</button></div>{simple&&<div className="parent-tip"><span>NÓI NGẮN HƠN</span><p>“{active.remember}”</p><p>Chỉ chọn một ý, làm mẫu bằng lời hoặc một hành động an toàn rồi hỏi con muốn thử không.</p></div>}{example&&<div className="parent-tip"><span>ĐỔI VAI VỚI CON</span><p>“Nếu bố/mẹ là nhân vật trong câu chuyện, con sẽ khuyên bố/mẹ thế nào?” Sau đó dùng lời con để cùng diễn lại cách xử lý.</p></div>}</>}
{step===4&&<><span className="content-label">CÙNG LÀM THỬ</span><blockquote>{active.practice}</blockquote><div className="remember-box"><Sparkles size={20}/><div><small>ĐIỀU CON CẦN NHỚ</small><h3>{active.remember}</h3></div></div><h3>Áp dụng khi có dịp</h3><p>{active.mission}</p><div className="parent-tip"><span>NẾU CON CHƯA MUỐN THAM GIA</span><p>Cho con quan sát trước hoặc chọn lúc khác. Không ép kể chuyện riêng hay so sánh với anh chị em.</p></div></>}
{step===5&&<><p className="muted">Ghi nhận cho từng con đã tham gia. Có thể quay lại cập nhật sau khi con áp dụng ngoài đời.</p>{!family?.children.length&&<div className="empty-state"><Users/><h3>Thêm con để lưu buổi học đầu tiên</h3><button className="button" onClick={()=>openChild()} disabled={!family}>Thêm hồ sơ con</button></div>}{family?.children.map(c=><div className="outcome-row" key={c.id}><label className="check-label"><Checkbox checked={selected.includes(c.id)} onCheckedChange={checked=>setSelected(s=>checked?[...new Set([...s,c.id])]:s.filter(id=>id!==c.id))}/><strong>{c.name}</strong></label>{selected.includes(c.id)&&<><Choice label={'Ghi nhận cho '+c.name} value={outcomes[c.id]?.status||'learned'} onChange={v=>setOutcomes(o=>({...o,[c.id]:{note:o[c.id]?.note||'',status:v as LearningRecord['status']}}))} items={Object.entries(statusText).map(([value,label])=>({value,label}))}/><label className="field">Ghi chú cho {c.name} <span>(không bắt buộc)</span><textarea maxLength={1200} rows={3} value={outcomes[c.id]?.note||''} onChange={e=>setOutcomes(o=>({...o,[c.id]:{status:o[c.id]?.status||'learned',note:e.target.value}}))} placeholder="Ví dụ: Con đã tự mở lời nhưng còn hơi ngại."/></label></>}</div>)}</>}
<div className="reader-actions"><button className="button secondary" disabled={step===0||saving} onClick={()=>changeStep(step-1)}><ArrowLeft size={17}/> Quay lại</button>{step<5?<button className="button" onClick={()=>changeStep(step+1)}>Tiếp theo <ArrowRight size={17}/></button>:<button className="button" disabled={saving||!family||!selected.length} onClick={finish}><Check size={17}/>{saving?'Đang lưu…':'Hoàn thành và lưu bài'}</button>}</div></section></div></>:<>
<div className="page-heading"><div><p className="eyebrow">MỖI NGÀY CÙNG CON</p><h1>{headings[view][0]}</h1><p>{headings[view][1]}</p></div><span className="date-pill"><CalendarDays size={17}/>{new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',year:'numeric'}).format(now)}</span></div>
{loading&&<div className="loading-row"><Skeleton className="h-8 w-48"/><span>Đang mở không gian gia đình…</span></div>}
{view==='today'&&<>
{completed&&<section className="completion-banner" role="status"><span className="completion-icon"><Check size={24}/></span><div><h2>Đã hoàn thành bài {completed.id}</h2><p>{completed.title}</p><small>Đã lưu ghi nhận. Chọn một bài trong lộ trình bên dưới hoặc nghỉ và quay lại sau.</small></div><button className="icon-button" aria-label="Đóng thông báo hoàn thành" onClick={()=>setCompleted(null)}><X size={18}/></button></section>}
{!loading&&family&&<section className="home-learning" aria-label="Tiến độ và lộ trình học"><div className="learning-heading"><div><h2>Hành trình của {scopeLabel}</h2><p>{total} / {lessons.length} bài đã học</p></div>{!!family?.children.length&&<Choice label="Hành trình học của" value={filterChild} onChange={setFilterChild} items={[{value:'all',label:'Cả gia đình'},...family.children.map(c=>({value:c.id,label:c.name}))]}/>}</div><Progress value={total/lessons.length*100} aria-label="Tiến độ các bài đã học"/>
<div className="home-learning-grid"><section className="panel recent-learning"><div className="learning-section-title"><Check size={20}/><h3>Bài đã học</h3></div>{path.recent.length?<><ol className="progress-lesson-list">{path.recent.slice(0,3).map(({lesson,record})=><li key={lesson.id}><button onClick={()=>setPreview(lesson)}><span className="path-number done"><Check size={16}/></span><span><strong>Bài {lesson.id} · {lesson.title}</strong><small>{statusText[record.status]} · {record.date.split('-').reverse().join('/')}</small></span><BookOpen size={16}/></button></li>)}</ol><button className="text-button" onClick={()=>go('journey')}>Xem tất cả {total} bài đã học <ArrowRight size={16}/></button></>:<p className="path-empty">Chưa có bài đã học. Khi hoàn thành và lưu bài, tiến độ sẽ xuất hiện ở đây.</p>}</section>
<section className="panel next-learning"><div className="learning-section-title"><ArrowRight size={20}/><h3>Lộ trình các bài kế tiếp</h3></div>{path.upcoming.length?<><ol className="progress-lesson-list">{path.upcoming.slice(0,3).map((lesson,i)=><li key={lesson.id}><button onClick={()=>start(lesson)} aria-label={'Học bài '+lesson.id+' · '+lesson.title}><span className={'path-number '+(i===0?'next':'')}>{lesson.id}</span><span><strong>{lesson.title}</strong><small>{i===0?'Bài tiếp theo':'Học tiếp sau đó'} · {lesson.category} · {lesson.minutes} phút</small></span><ArrowRight size={16}/></button></li>)}</ol><button className="button" onClick={()=>{if(todayLesson)start(todayLesson)}}>Học bài tiếp theo <ArrowRight size={16}/></button><button className="text-button" onClick={()=>{const index=segments.findIndex((start,i)=>i<segments.length-1&&path.upcoming[0].id>start&&path.upcoming[0].id<=segments[i+1]);setSegment(String(Math.max(index,0)));go('schedule')}}>Xem lộ trình 365 bài <ChevronRight size={16}/></button></>:<div className="path-complete"><Sparkles size={25}/><h3>Đã học đủ 365 bài!</h3><p>Chọn một kỹ năng để ôn lại và tiếp tục thực hành trong cuộc sống.</p><button className="button secondary" onClick={()=>go('library')}>Chọn bài để ôn</button></div>}</section></div></section>}
{todayLesson&&<div className="dashboard-grid"><section className="lesson-hero"><div className="hero-copy"><span className="hero-tag"><Sparkles size={15}/> GỢI Ý TIẾP THEO</span><p className="hero-category">{todayLesson.category.toUpperCase()} · BÀI {String(todayLesson.id).padStart(2,'0')}</p><h2>{todayLesson.title}</h2><p>{todayLesson.goal}</p><div className="hero-meta"><Clock size={16}/> {todayLesson.minutes} phút <span>•</span> Tiểu học · Dưới 12 tuổi</div><div className="hero-actions"><button className="button golden" onClick={()=>start(todayLesson)}>Bắt đầu hướng dẫn <ArrowRight size={17}/></button><button className="read-ahead" onClick={()=>setPreview(todayLesson)}>Đọc trước bài <BookOpen size={15}/></button></div></div><img className="hero-art" src="family-reading.png" alt="Cha mẹ và các con cùng đọc sách"/></section><aside className="panel tonight"><span className="icon-tile"><BookOpen/></span><p className="eyebrow">MỘT NĂM KHÁM PHÁ</p><h2>Mỗi bài, một kỹ năng</h2><div className="big-time">365</div><p>Chọn bài con đang cần. Học một bài, nghỉ một chút, hoặc quay lại luyện thêm.</p><button className="text-button" onClick={()=>go('library')}>Chọn bài để học <ChevronRight size={15}/></button><span className="small-status">Không có giờ học cố định</span></aside></div>}
{resume&&<div className="resume-banner"><BookOpen size={19}/><p>Đang đọc: <strong>{lessons[resume.id-1].title}</strong><small>Bước {resume.step+1} · {stages[resume.step]}</small></p><button className="text-button" onClick={()=>start(lessons[resume.id-1],resume.step)}>Tiếp tục <ArrowRight size={16}/></button></div>}
<div className="dashboard-lower"><section><div className="section-title"><h2>Một buổi học, thật nhẹ nhàng</h2><span>CHA MẸ DẪN DẮT · CON THỰC HÀNH</span></div><div className="steps-overview">{['Đọc trước câu chuyện','Trò chuyện cùng con','Cùng làm, cùng nhớ'].map((s,i)=><div className="panel" key={s}><span className="step-number">0{i+1}</span><h3>{s}</h3><p>{['Mục tiêu rõ ràng, lời dẫn có sẵn.','Câu hỏi mở để lắng nghe con.','Một việc nhỏ để áp dụng ngày mai.'][i]}</p></div>)}</div></section></div>
<div className="family-strip"><span className="category-icon tone-2"><Heart size={24}/></span><div><h3>{family?.children.length?'Những bước nhỏ của gia đình':'Bắt đầu với hồ sơ của con'}</h3><p>{family?.children.length?`${total} bài đã cùng học · ${practices} ghi nhận thực hành`:'Thêm biệt danh để lưu tiến bộ riêng cho từng con.'}</p></div><button className="button secondary" disabled={!family} onClick={()=>family?.children.length?go('journey'):openChild()}>{family?.children.length?'Xem hành trình':'Thêm con'} <ArrowRight size={16}/></button></div></>}
{view==='library'&&<><div className="filter-bar"><label className="search-field"><Search size={19}/><input aria-label="Tìm bài học" placeholder="Tìm kỹ năng, tình huống…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/>{query&&<button aria-label="Xóa tìm kiếm" onClick={()=>{setQuery('');setPage(1)}}><X size={16}/></button>}</label><Choice label="Chủ đề bài học" value={category} onChange={v=>{setCategory(v);setPage(1)}} items={categories.map(c=>({value:c,label:c}))}/></div><p className="result-count" role="status">{filtered.length} bài học · Tất cả đều sẵn sàng để học</p><div className="lesson-grid">{filtered.slice((visiblePage-1)*18,visiblePage*18).map(l=><LessonCard key={l.id} lesson={l} onOpen={()=>setPreview(l)} done={learnedIds.has(l.id)}/>)}</div>{!filtered.length?<div className="empty-state"><Search/><h3>Chưa tìm thấy bài phù hợp</h3><p>Thử một từ ngắn hơn hoặc chọn tất cả chủ đề.</p><button className="button secondary" onClick={()=>{setQuery('');setCategory('Tất cả');setPage(1)}}>Xem tất cả bài học</button></div>:<Pagination aria-label="Các trang bài học" className="library-pages"><button className="button secondary" disabled={visiblePage===1} onClick={()=>{setPage(visiblePage-1);window.scrollTo(0,0)}}><ArrowLeft size={16}/> Trang trước</button><span>Trang {visiblePage} / {pages}</span><button className="button secondary" disabled={visiblePage===pages} onClick={()=>{setPage(visiblePage+1);window.scrollTo(0,0)}}>Trang sau <ArrowRight size={16}/></button></Pagination>}</>}
{view==='schedule'&&<><div className="roadmap-intro panel"><div><h2>Học theo nhịp của con</h2><p>Mỗi ngày một bài là gợi ý cho một năm. Có thể bỏ qua thứ tự, học bù hoặc ôn lại; app không gửi nhắc theo giờ.</p></div><Choice label="Chọn chặng học" value={segment} onChange={setSegment} items={segments.slice(0,-1).map((start,i)=>({value:String(i),label:'Chặng '+(i+1)+' · Bài '+(start+1)+'–'+segments[i+1]}))}/></div><div className="section-title"><h2>Chặng {Number(segment)+1}</h2><span>{segments[Number(segment)+1]-segments[Number(segment)]} bài · Học bất cứ lúc nào</span></div><div className="schedule-list">{lessons.slice(segments[Number(segment)],segments[Number(segment)+1]).map(l=><button key={l.id} className={'schedule-item '+(todayLesson?.id===l.id?'is-today':'')} onClick={()=>setPreview(l)}><span className="schedule-day">{String(l.id).padStart(2,'0')}<small>BÀI</small></span><span className="schedule-title"><strong>{l.title}</strong><small>{l.category} · {l.minutes} phút</small></span>{learnedIds.has(l.id)?<Check size={18}/>:<ChevronRight size={18}/>}</button>)}</div></>}
{view==='journey'&&<><div className="stats-grid"><div className="panel"><BookOpen/><strong>{total}<small> / 365</small></strong><span>Bài đã cùng học</span></div><div className="panel"><HandHeart/><strong>{practices}</strong><span>Ghi nhận đã thực hành</span></div><div className="panel"><Users/><strong>{family?.children.length||0}</strong><span>Con đang đồng hành</span></div></div><div className="section-title"><h2>Nhật ký của gia đình</h2><Choice label="Lọc theo con" value={filterChild} onChange={setFilterChild} items={[{value:'all',label:'Tất cả các con'},...(family?.children.map(c=>({value:c.id,label:c.name}))||[])]}/></div>{!family?.records.filter(r=>filterChild==='all'||r.childId===filterChild).length?<div className="empty-state panel"><Heart size={35}/><h2>Buổi học đầu tiên đang chờ</h2><p>Sau khi hướng dẫn con, ghi nhận điều con đã thử ở bước cuối bài học.</p><button className="button" onClick={()=>{if(todayLesson)start(todayLesson);else go('library')}}>Cùng con học bài tiếp theo <ArrowRight size={17}/></button></div>:<div className="journal-list">{family.records.filter(r=>filterChild==='all'||r.childId===filterChild).sort((a,b)=>b.date.localeCompare(a.date)).map(r=><article className="panel journal-entry" key={r.childId+':'+r.lessonId}><div className="journal-top"><span className={'badge status-'+r.status}>{statusText[r.status]}</span><small>{r.date.split('-').reverse().join('/')}</small></div><h3>{lessons[r.lessonId-1].title}</h3><p className="journal-child">{family.children.find(c=>c.id===r.childId)?.name}</p>{r.note&&<p className="journal-note">{r.note}</p>}<div className="journal-mission"><strong>Tiếp tục thực hành</strong><p>{lessons[r.lessonId-1].mission}</p></div><button className="text-button" onClick={()=>start(lessons[r.lessonId-1],5,r.childId)}>Cập nhật ghi nhận <Pencil size={14}/></button></article>)}</div>}</>}
{view==='family'&&<><div className="section-title"><h2>Các con của tôi</h2><button className="button" disabled={!family||family.children.length>=12} onClick={()=>openChild()}><Plus size={17}/> Thêm con</button></div>{!family?.children.length?<div className="empty-state panel"><Users size={35}/><h2>Mỗi con, một hành trình riêng</h2><p>Chỉ cần biệt danh. Các bài học dùng chung cho trẻ tiểu học dưới 12 tuổi.</p><button className="button" disabled={!family} onClick={()=>openChild()}>Thêm hồ sơ đầu tiên</button></div>:<div className="children-grid">{family.children.map((c,i)=>{const count=family.records.filter(r=>r.childId===c.id).length;return <article key={c.id} className="panel child-card"><div className="child-top"><span className={'child-avatar tone-'+(i%6+1)}>{c.name.slice(0,1).toUpperCase()}</span><div><h2>{c.name}</h2><p>Tiểu học · Dưới 12 tuổi</p></div></div><p className="child-count">{count} / 365 bài đã cùng học</p><Progress value={count/lessons.length*100} aria-label={'Tiến độ của '+c.name}/><div className="child-actions"><button className="text-button" onClick={()=>openChild(c)}><Pencil size={15}/> Sửa hồ sơ</button><button className="text-button danger" onClick={()=>setDeleteChild(c)} aria-label={'Xóa hồ sơ '+c.name}><Trash2 size={15}/> Xóa</button></div></article>})}</div>}<div className="privacy-note"><ShieldCheck size={22}/><p>{typeof window !== 'undefined' && (window as typeof window & {__staticWeb?: boolean}).__staticWeb ? 'Hồ sơ và ghi nhận được lưu ngay trên thiết bị này (trong trình duyệt của bạn). Không cần đăng nhập và không gửi dữ liệu đi đâu cả; mở trên thiết bị khác sẽ có hành trình riêng.' : 'Hồ sơ và ghi nhận được lưu trong không gian riêng của tài khoản. Đăng nhập cùng tài khoản trên máy tính và điện thoại để tiếp tục hành trình.'}</p></div></>}
<footer className="app-footer"><span><Heart size={13}/> Đồng hành, không so sánh.</span><span>365 bài học · Cha mẹ hướng dẫn trực tiếp</span></footer></>}
</div></main><nav className="mobile-nav" aria-label="Điều hướng chính">{navigation.map(n=><button key={n.id} aria-current={view===n.id?'page':undefined} className={view===n.id?'active':''} onClick={()=>{setActive(null);go(n.id)}}><n.icon size={20}/><span>{n.id==='library'?'Thư viện':n.title}</span></button>)}</nav>
<Dialog open={!!preview} onOpenChange={open=>{if(!open)setPreview(null)}}><DialogContent className="preview-dialog"><DialogHeader><DialogTitle>{preview?.title}</DialogTitle><DialogDescription>{preview?.category} · {preview?.minutes} phút · Đọc trước cho cha mẹ</DialogDescription></DialogHeader>{preview&&<><div className="goal-box"><Lightbulb size={20}/><p>{preview.goal}</p></div><h3>Câu chuyện hôm nay</h3><p>{preview.story}</p><h3>Câu hỏi cho con</h3><p>{preview.question}</p><h3>Cách giải thích</h3><p>{preview.explain}</p><h3>Cùng thực hành</h3><p>{preview.practice}</p><div className="remember-box"><Sparkles size={20}/><p>{preview.remember}</p></div><h3>Việc nhỏ sau bài học</h3><p>{preview.mission}</p><button className="button" onClick={()=>start(preview)}>Bắt đầu hướng dẫn <ArrowRight size={17}/></button></>}</DialogContent></Dialog>
<Dialog open={childDialog} onOpenChange={setChildDialog}><DialogContent><DialogHeader><DialogTitle>{editChild?'Sửa hồ sơ con':'Thêm con vào gia đình'}</DialogTitle><DialogDescription>Dùng biệt danh để lưu hành trình học của con. Không cần nhập tuổi hay lớp.</DialogDescription></DialogHeader><form onSubmit={submitChild} className="child-form"><label className="field">Biệt danh của con<input autoFocus required maxLength={40} value={childName} onChange={e=>setChildName(e.target.value)} placeholder="Ví dụ: Bé Mít"/></label><button type="submit" className="button" disabled={saving||!childName.trim()}>{saving?'Đang lưu…':'Lưu hồ sơ'}</button></form></DialogContent></Dialog>
<AlertDialog open={!!deleteChild} onOpenChange={open=>{if(!open)setDeleteChild(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Xóa hồ sơ {deleteChild?.name}?</AlertDialogTitle><AlertDialogDescription>Hồ sơ và toàn bộ ghi nhận học tập của con sẽ bị xóa. Các con khác không bị ảnh hưởng.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Giữ lại</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={e=>{e.preventDefault();void removeChild()}}>{saving?'Đang xóa…':'Xóa hồ sơ'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
<Toaster position="top-center" richColors/></SidebarProvider>}



