import {additionalRows} from './year-curriculum';
export const categories = ['Tất cả','Giao tiếp','Cảm xúc','Tự lập','Tình bạn','An toàn','Trách nhiệm'];
type Row = [string,string,string,string,string,string,string,string,string];
const rows: Row[] = [
['Khi cần giúp đỡ, con nói thế nào?','Giao tiếp','Con biết nói rõ khó khăn và nhờ người phù hợp giúp.','An kéo mãi mà không mở được hộp bút. Bạn bắt đầu bực mình. Cô giáo đang đứng gần đó, nhưng An chưa biết nói gì.','Nếu là An, con sẽ nói với cô thế nào?','Gọi người phù hợp, nói điều đang khó, rồi đề nghị giúp: “Cô ơi, con chưa mở được hộp bút. Cô giúp con với ạ.”','Dùng một chiếc hộp để đóng vai. Đổi lượt: con nhờ giúp, rồi cha mẹ nhờ con giúp.','Gặp khó, con nói rõ và nhờ giúp.','Ngày mai, khi gặp việc chưa làm được, con thử nói rõ điều cần giúp.'],
['Gọi tên cảm xúc của con','Cảm xúc','Con nhận biết và nói được cảm xúc của mình.','Mai vui khi được chơi cùng bạn, nhưng buồn vì bạn phải về sớm. Mai tự hỏi sao mình vừa vui vừa buồn.','Con nghĩ Mai đang cảm thấy gì? Con từng có hai cảm xúc cùng lúc chưa?','Cảm xúc có thể cùng xuất hiện. Mọi cảm xúc đều được lắng nghe. Con có thể nói: “Con thấy buồn vì…” mà không cần giấu đi.','Mỗi người chọn một cảm xúc hôm nay và kể điều đã xảy ra. Cho phép con chỉ tay hoặc vẽ nếu chưa muốn nói.','Cảm xúc nào cũng có thể nói ra.','Hỏi nhau “Hôm nay con cảm thấy thế nào?” và lắng nghe hết câu.'],
['Bình tĩnh khi đang tức giận','Cảm xúc','Con biết dừng lại trước khi phản ứng làm đau mình hoặc người khác.','Bình đang xây tháp thì em vô tình làm đổ. Bình nắm chặt tay và muốn hét lên.','Bình có thể làm gì trước khi nói chuyện với em?','Tức giận là cảm xúc bình thường. Hãy đặt đồ xuống, bước về chỗ an toàn, thở chậm vài nhịp rồi nói điều mình cần.','Đóng vai tháp đổ bằng lời kể. Tập câu: “Anh đang giận. Anh cần nghỉ một chút.” Không cố gây giận thật.','Dừng một chút, rồi nói điều mình cần.','Chọn một góc yên tĩnh trong nhà để nghỉ khi cần.'],
['Lắng nghe đến hết câu','Giao tiếp','Con biết chờ người khác nói xong rồi đáp lời.','Lan muốn kể chuyện ở trường nhưng Nam liên tục chen vào kể chuyện của mình. Lan dừng lại, không muốn kể nữa.','Nếu là Lan, con sẽ cảm thấy thế nào?','Lắng nghe là để người kia có thời gian nói. Hướng sự chú ý về người nói theo cách con thấy thoải mái, chờ họ dừng rồi hỏi thêm.','Mỗi người kể một chuyện trong một phút. Người nghe nhắc lại một điều mình nhớ trước khi đổi lượt.','Nghe hết câu, hiểu thêm một chút.','Trong bữa ăn, dành một lượt kể chuyện trọn vẹn cho mỗi người.'],
['Xin lỗi và cùng sửa lỗi','Giao tiếp','Con biết xin lỗi cụ thể và đề nghị sửa điều đã làm.','Hà vô ý làm rách tranh của bạn. Hà nói “xin lỗi” rồi chạy đi, còn bạn vẫn buồn.','Ngoài xin lỗi, Hà có thể làm gì nữa?','Nói rõ việc mình làm, thừa nhận ảnh hưởng và đề nghị sửa: “Mình làm rách tranh của bạn. Mình xin lỗi. Mình giúp bạn dán lại nhé?”','Đóng vai làm đổ bút trên bàn. Tập xin lỗi và cùng nhặt lại. Không ép người kia phải hết buồn ngay.','Xin lỗi bằng lời, sửa lỗi bằng việc.','Nếu có sơ suất nhỏ, cùng con tìm một cách sửa phù hợp.'],
['Lời nhờ lịch sự trong gia đình','Giao tiếp','Con diễn đạt yêu cầu rõ ràng và biết chờ phản hồi.','Minh hét “Nước!” khi đang ăn. Mẹ chưa hiểu con muốn lấy bình nước hay cần rót nước.','Minh có thể nói thế nào để mẹ hiểu?','Nói tên người mình nhờ và việc cần giúp: “Mẹ ơi, mẹ chuyền giúp con bình nước nhé.” Người khác có thể đang bận; con có thể chờ hoặc hỏi lúc phù hợp.','Cha mẹ và con lần lượt nhờ nhau chuyền một đồ vật an toàn bằng một câu đầy đủ.','Nói rõ, nói nhẹ, chờ một chút.','Tập một lời nhờ trong sinh hoạt ngày mai.'],
['Ôn luyện: Một ngày ở lớp','Giao tiếp','Con kết hợp lắng nghe, nhờ giúp và xin lỗi.','An chưa hiểu bài, bạn bên cạnh đang kể chuyện, rồi An vô tình làm rơi hộp bút của bạn.','An nên xử lý từng việc theo thứ tự nào?','Không cần làm mọi thứ cùng lúc. Nhặt bút và xin lỗi; lắng nghe bạn; khi phù hợp thì nhờ cô giải thích bài. Có thể có nhiều thứ tự hợp lý.','Mỗi người đóng một vai. Diễn lại ba tình huống; cho con chọn cách nói bằng lời riêng.','Từng việc một, con có thể xử lý.','Chọn một câu nói trong tuần mà con muốn dùng lại.'],
['Con tự chuẩn bị cặp sách','Tự lập','Con kiểm tra đồ học bằng một danh sách ngắn.','Sáng đi học, Tú mới phát hiện vở vẫn nằm trên bàn. Cả nhà phải tìm vội.','Tối trước, Tú có thể chuẩn bị thế nào?','Xem thời khóa biểu cùng người lớn, chọn sách vở cần thiết, kiểm tra bút và đồ cá nhân rồi đặt cặp ở chỗ quen thuộc.','Cùng lập danh sách ba đến năm món và để con kiểm tra cặp. Cha mẹ hỗ trợ khi con hỏi.','Kiểm tra trước, sáng thảnh thơi.','Ngày mai, để con tự đánh dấu danh sách đồ học.'],
['Mỗi đồ vật có một chỗ','Tự lập','Con biết cất đồ vào vị trí dễ nhớ.','Bút màu nằm dưới ghế, sách ở trên giường. Khi cần vẽ, Vy tìm mãi không thấy đủ đồ.','Con sẽ chọn chỗ nào cho bút màu và sách?','Cất đồ gần nơi dùng và gom cùng loại giúp dễ tìm. Chọn ít vị trí rõ ràng thay vì sắp xếp quá phức tạp.','Chọn một ngăn nhỏ, cùng phân loại và để con quyết định vị trí cho ba món đồ.','Dùng xong, đưa đồ về nhà của nó.','Cất lại một nhóm đồ sau khi sử dụng.'],
['Việc nào làm trước?','Tự lập','Con biết chọn thứ tự cho những việc cần làm.','Sau giờ học, Khoa muốn chơi, làm bài và chuẩn bị đồ cho ngày mai. Bạn thấy việc nào cũng đang chờ.','Khoa cần biết điều gì để chọn việc trước?','Xem việc có giờ cố định, việc cần hoàn thành và thời gian nghỉ. Nhờ người lớn cùng lập một lịch vừa sức, có chỗ để chơi.','Viết hoặc vẽ ba việc trên giấy, cùng xếp thứ tự. Hỏi con vì sao chọn như vậy.','Có kế hoạch nhỏ, bớt vội vàng.','Thử thực hiện một kế hoạch ba việc rồi cùng điều chỉnh.'],
['Thử lại khi chưa làm được','Cảm xúc','Con biết chia việc khó thành bước nhỏ và tìm hỗ trợ.','Linh gấp máy bay nhưng cánh cứ lệch. Bạn nói: “Con chẳng làm được gì cả!”','Con có thể nói gì với Linh?','Một lần chưa thành công không nói lên khả năng của con. Thử một bước nhỏ, đổi cách hoặc nhờ hướng dẫn. Nghỉ một chút cũng được.','Cùng gấp một tờ giấy theo hai bước. Khen sự thay đổi cách làm và nỗ lực cụ thể.','Chưa làm được, mình thử cách khác.','Chọn một việc nhỏ muốn thử lại, không cần hoàn hảo.'],
['Điều con cần và điều con muốn','Trách nhiệm','Con bước đầu phân biệt nhu cầu thiết yếu và mong muốn.','Bút của An đã hết mực. Trong cửa hàng có bút mới và một bộ đồ chơi hấp dẫn, nhưng tiền chỉ đủ mua một món.','An cần món nào để đi học? Món nào có thể chờ?','Điều cần giúp sinh hoạt hoặc học tập. Điều muốn mang lại niềm vui nhưng có thể đợi. Mong muốn không xấu; mình cân nhắc trước khi mua.','Chọn bốn món quen thuộc và trò chuyện món nào đang cần trong hoàn cảnh hiện tại.','Biết mình cần gì trước khi chọn.','Trước một lần mua sắm, cùng nói lý do chọn một món.'],
['Một việc nhà của con','Tự lập','Con tự thực hiện một việc nhà an toàn, vừa sức.','Sau bữa ăn, mọi người đều dọn. Bảo muốn giúp nhưng không biết bắt đầu từ đâu.','Bảo có thể giúp việc gì an toàn?','Chọn một việc vừa sức như xếp khăn hoặc cất đồ chơi. Nhờ người lớn hướng dẫn; không tự dùng hóa chất, vật sắc hay đồ nóng.','Cùng xếp khăn hoặc cất sách. Người lớn làm mẫu một lần rồi cho con thử.','Con góp một tay, nhà mình nhẹ hơn.','Chọn một việc nhà nhỏ để tự làm vào ngày mai.'],
['Ôn luyện: Buổi sáng chủ động','Tự lập','Con kết hợp chuẩn bị, sắp xếp và nhờ hỗ trợ.','Sáng nay gia đình có 20 phút trước khi đi học. Cặp chưa kiểm tra, áo ở chỗ cũ, con còn cần ăn sáng.','Việc gì có thể chuẩn bị từ tối trước?','Chuẩn bị trước những việc có thể làm. Buổi sáng ưu tiên nhu cầu cơ bản và nhờ giúp nếu lịch quá gấp. Không bỏ ăn để hoàn thành thử thách.','Cùng đóng vai buổi tối và buổi sáng bằng ba tấm giấy ghi việc cần làm.','Chuẩn bị hôm nay, dễ dàng ngày mai.','Chọn một thói quen chuẩn bị để cả nhà duy trì.'],
['Xin tham gia trò chơi cùng bạn','Tình bạn','Con biết mở lời và ứng xử khi chưa được tham gia.','Một nhóm đang chơi ghép hình. Huy đứng ngoài muốn chơi nhưng chưa biết nói gì.','Huy có thể mở lời thế nào?','Con có thể hỏi: “Mình chơi cùng được không? Mình giúp phần nào nhé?” Nếu chưa thuận tiện, hỏi lượt sau hoặc tìm hoạt động khác.','Cha mẹ đóng vai nhóm bạn. Tập cả khi được đồng ý và khi cần chờ.','Mở lời thân thiện, tôn trọng câu trả lời.','Thử làm quen hoặc mời một bạn cùng chơi khi phù hợp.'],
['Chờ đến lượt của mình','Tình bạn','Con thực hành chia lượt bằng thỏa thuận rõ ràng.','Hai bạn cùng muốn dùng một hộp màu. Cả hai kéo hộp về phía mình.','Có cách nào để cả hai đều được dùng?','Thỏa thuận thứ tự hoặc chia đồ có thể chia. Thời gian chờ cần rõ và vừa sức; người lớn hỗ trợ nếu hai bạn chưa thống nhất.','Chọn một đồ chơi, lần lượt dùng trong khoảng ngắn đã thống nhất, rồi tự chuyển lượt.','Ai cũng có lượt, mình cùng vui.','Áp dụng chia lượt vào một hoạt động gia đình.'],
['Khi hai bạn không đồng ý','Tình bạn','Con nói nhu cầu và cùng tìm phương án công bằng.','Mai muốn vẽ biển, Nam muốn vẽ rừng trên cùng một tờ giấy. Hai bạn bắt đầu cãi nhau.','Có ý tưởng nào giữ được điều cả hai thích?','Mỗi người nói ý muốn, lắng nghe người kia rồi đề xuất lựa chọn: chia phần giấy, vẽ hai tranh, hoặc chọn chủ đề kết hợp.','Hai người cùng quyết định chủ đề một bức tranh. Mỗi người đưa một phương án rồi cùng chọn.','Nói điều mình muốn, nghe điều bạn cần.','Trong một bất đồng nhỏ, thử nêu hai cách giải quyết.'],
['Khi bị trêu chọc làm buồn','An toàn','Con biết tìm hỗ trợ khi bị làm tổn thương.','Một bạn liên tục gọi Tuấn bằng tên khiến Tuấn khó chịu, dù Tuấn đã đề nghị dừng lại.','Tuấn có thể tìm ai để được giúp?','Nếu thấy an toàn, nói “Mình không thích. Bạn dừng lại.” Rời đến nơi có người lớn và kể rõ sự việc. Con không có lỗi vì bị trêu chọc.','Tập kể với người lớn tin cậy: ai đã làm gì, ở đâu, con cần hỗ trợ gì. Không yêu cầu con diễn lại lời xúc phạm.','Con có quyền được tôn trọng và giúp đỡ.','Cùng chọn hai người lớn con có thể tìm đến ở trường.'],
['Mỗi người có một điểm riêng','Tình bạn','Con thể hiện sự tôn trọng khác biệt.','Bạn mới nói chậm hơn và thích trò chơi khác cả nhóm. Một vài bạn thấy lạ.','Làm sao để bạn mới cảm thấy được chào đón?','Mỗi người có sở thích, cách học và khả năng riêng. Hỏi bạn muốn tham gia thế nào, không trêu chọc hay ép bạn giống mình.','Mỗi người kể một sở thích khác nhau. Cùng tìm hoạt động có thể chia sẻ mà vẫn tôn trọng lựa chọn riêng.','Khác nhau vẫn có thể chơi cùng.','Hỏi một người thân về điều họ thích và lắng nghe.'],
['Cùng nhau làm một việc','Tình bạn','Con biết nhận phần việc rõ ràng và phối hợp.','Cả nhà làm một tấm thiệp. Ai cũng muốn tô màu, nhưng chưa ai gấp giấy hay viết lời chúc.','Mình có thể chia việc thế nào?','Liệt kê phần việc, hỏi mỗi người muốn và có thể làm gì rồi thống nhất. Có thể đổi vai để mọi người đều được thử.','Cùng làm một tấm thiệp hoặc xếp một góc sách. Mỗi người nhận một phần cụ thể.','Biết phần mình, giúp phần chung.','Ghi nhận một điều con đã góp cho hoạt động chung.'],
['Ôn luyện: Một buổi chơi vui','Tình bạn','Con vận dụng mở lời, chia lượt và giải quyết bất đồng.','Ba bạn muốn chơi hai trò khác nhau và chỉ có một bộ đồ chơi. Một bạn mới muốn tham gia.','Làm thế nào để mọi người đều được lắng nghe?','Mời bạn mới, nghe từng ý kiến, chọn cách chia lượt. Nếu chưa thống nhất, nhờ người lớn hỗ trợ thay vì ép một bạn chịu thiệt.','Đóng vai cả buổi chơi bằng đồ vật đại diện cho các bạn. Để con đề xuất luật chia lượt.','Chơi vui là cùng được tôn trọng.','Chọn một thỏa thuận để thử trong lần chơi tiếp theo.'],
['Người lớn con có thể tin cậy','An toàn','Con xác định người lớn có thể tìm đến khi cần giúp.','Có chuyện khiến My lo lắng. My muốn kể nhưng không biết bắt đầu với ai.','My có thể tìm ai ở nhà và ở trường?','Chọn người biết lắng nghe và giúp con an toàn. Nếu người đầu tiên chưa giúp được, tiếp tục kể với người lớn tin cậy khác.','Cùng lập danh sách ba người và cách liên hệ. Không cần đưa thông tin liên hệ lên app.','Chưa được giúp, con tiếp tục tìm người giúp.','Nhắc lại tên một người có thể hỗ trợ ở trường.'],
['Nếu con bị lạc','An toàn','Con biết dừng ở nơi an toàn và tìm hỗ trợ phù hợp.','Ở siêu thị, An quay lại không còn thấy bố mẹ. Bạn định chạy ra ngoài tìm.','An nên làm gì trước tiên?','Ở lại khu vực an toàn, gần nơi vừa tách nhau nếu có thể; nhờ nhân viên có quầy hoặc bảo vệ hỗ trợ liên hệ gia đình. Không đi theo người lạ ra chỗ vắng.','Chỉ đóng vai ở nhà. Tập nói: “Cháu bị lạc, cô/chú giúp cháu liên hệ gia đình.”','Dừng an toàn, nhờ đúng người giúp.','Trước lần đi chơi tới, thống nhất điểm gặp và cách tìm giúp đỡ.'],
['Con có quyền nói không','An toàn','Con biết nói ra ranh giới và tìm hỗ trợ.','Một người muốn ôm nhưng bé không muốn. Bé lo rằng từ chối sẽ bị cho là không lễ phép.','Bé có thể chào theo cách nào khác?','Con có quyền từ chối tiếp xúc làm mình không thoải mái, kể cả với người quen. Có thể vẫy tay hoặc chào bằng lời. Người lớn cần tôn trọng câu trả lời.','Hỏi “Con muốn đập tay không?” và thực sự tôn trọng cả câu có lẫn không. Không ép diễn cảnh đụng chạm.','Cơ thể của con, con được lên tiếng.','Cho con chọn cách chào phù hợp với sự thoải mái của mình.'],
['Chuyện làm con lo không cần giữ kín','An toàn','Con biết kể với người lớn khi bị yêu cầu giữ chuyện khiến mình bất an.','Một người dặn con giữ kín việc làm con sợ và nói rằng con sẽ gặp rắc rối nếu kể.','Con có thể tìm ai để nói chuyện?','Con được kể với người lớn tin cậy về điều khiến con sợ, đau hoặc không thoải mái. Kể để được bảo vệ không phải là làm sai.','Tập câu: “Con có chuyện lo lắng cần nói. Bố/mẹ nghe con nhé.” Không yêu cầu trẻ kể chuyện riêng trước mọi người.','Điều làm con lo, con được kể.','Nhắc con rằng cha mẹ sẵn sàng nghe và giúp, không trách con.'],
['Thông tin riêng tư trên mạng','An toàn','Con biết dừng và hỏi người lớn trước khi chia sẻ thông tin.','Một người trong trò chơi hỏi tên trường, địa chỉ nhà và ảnh của con để tặng quà.','Con nên làm gì trước khi trả lời?','Không gửi thông tin riêng tư, ảnh hay mã xác nhận cho người lạ. Dừng tương tác và nhờ phụ huynh kiểm tra, kể cả khi người đó nói là bạn quen.','Dùng tình huống giả trên giấy. Phân loại thông tin cần hỏi cha mẹ trước khi chia sẻ.','Dừng lại, hỏi người lớn trước khi gửi.','Cùng xem một cài đặt riêng tư trên thiết bị của gia đình.'],
['Tránh nguy hiểm, tìm người giúp','An toàn','Con biết tránh xa tình huống nguy hiểm và gọi người lớn.','Con nhìn thấy dây điện bị hở gần một vũng nước. Con muốn đến xem và sửa giúp.','Vì sao con nên dừng lại và báo người lớn?','Không chạm vào dây điện hay nước gần đó. Giữ khoảng cách, nhắc người khác tránh xa từ nơi an toàn và gọi người lớn. Trẻ không tự xử lý sự cố.','Chỉ dùng lời kể hoặc tranh; tuyệt đối không tạo tình huống nguy hiểm thật để thực hành.','Tránh xa nguy hiểm, gọi người lớn.','Cùng người lớn chỉ ra nơi trẻ không tự tiếp cận trong nhà.'],
['Ôn luyện: Chọn cách an toàn','An toàn','Con biết ưu tiên an toàn và tìm trợ giúp trong tình huống mới.','Trong ngày đi chơi, con có thể bị lạc, nhận lời mời đi riêng hoặc gặp vật lạ nguy hiểm.','Với mỗi tình huống, con sẽ dừng ở đâu và tìm ai?','Không cần tự giải quyết mọi việc. Giữ mình ở nơi an toàn, tránh tiếp cận nguy hiểm và nói với người lớn tin cậy.','Cha mẹ chọn hai tình huống bằng lời kể. Con nói cách tìm giúp; người lớn bổ sung nhẹ nhàng.','An toàn trước, tìm giúp ngay.','Nhắc lại kế hoạch liên lạc trước lần ra ngoài tiếp theo.'],
['Giữ lời hứa vừa sức','Trách nhiệm','Con biết hứa điều có thể làm và báo khi cần điều chỉnh.','Bảo hứa tưới cây nhưng quên vì bận học. Đến tối bạn muốn giấu chuyện đó.','Bảo có thể nói thật và sửa thế nào?','Hứa việc vừa sức, đặt lời nhắc và báo sớm khi không làm được. Thừa nhận rồi cùng tìm cách điều chỉnh có ích hơn giấu đi.','Chọn một cam kết nhỏ cho ngày mai, nói rõ lúc làm và ai hỗ trợ nếu cần.','Hứa vừa sức, khó thì nói thật.','Cùng xem lại cam kết, ghi nhận nỗ lực và điều chỉnh nếu cần.'],
['Nhìn lại: Con đã lớn lên thế nào?','Trách nhiệm','Con nhận ra tiến bộ và chọn kỹ năng muốn luyện tiếp.','Sau nhiều buổi học, con đã thử nhờ giúp, tự chuẩn bị và lắng nghe. Có việc dễ hơn, có việc vẫn còn khó.','Điều gì con tự hào? Điều gì con muốn cha mẹ cùng luyện thêm?','Tiến bộ là từng bước nhỏ. Có thể quên và học lại. Mỗi người có nhịp riêng, không cần so với anh chị em hay bạn bè.','Mỗi người kể một việc con đã thử và cùng chọn hai bài để ôn. Ghi nhận hành động cụ thể.','Mỗi ngày một chút, con đang lớn lên.','Chọn một kỹ năng để tiếp tục thực hành trong tuần tới.']
];
export type Lesson={id:number;title:string;category:string;goal:string;story:string;question:string;explain:string;practice:string;remember:string;mission:string;minutes:number};
export const lessons:Lesson[]=[...rows,...additionalRows].map((r,i)=>({id:i+1,title:r[0],category:r[1],goal:r[2],story:r[3],question:r[4],explain:r[5],practice:r[6],remember:r[7],mission:r[8],minutes:[6,7,8][i%3]}));
export const stages=['Chuẩn bị','Kể chuyện','Cùng trò chuyện','Giải thích','Thực hành','Ghi nhận'];
export function vnDate(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
export function elapsed(start:string,now=vnDate()){return Math.max(0,Math.floor((Date.parse(now+'T00:00:00Z')-Date.parse(start+'T00:00:00Z'))/86400000))}
