// The first choice is the suggested response. Rotate its position when building
// each lesson so children consider the content rather than a fixed letter.
export type ChoiceSet = [string, string, string, string];
export type LessonQuiz = { question: string; options: ChoiceSet; correctIndex: number };
export function makeQuiz(choices: ChoiceSet, lessonId: number): LessonQuiz {
  const correctIndex = (lessonId - 1) % 4;
  const options = [...choices] as ChoiceSet;
  [options[0], options[correctIndex]] = [options[correctIndex], options[0]];
  return { question: 'Trong tình huống này, con chọn cách nào phù hợp nhất?', options, correctIndex };
}

// These follow the original 30 lesson IDs, which are also used by saved records.
export const legacyChoices: ChoiceSet[] = [
  ['Nói: “Cô ơi, con chưa mở được hộp bút. Cô giúp con với ạ.”', 'Ném hộp bút xuống sàn vì bực.', 'Chỉ hét lên mà không nói mình cần gì.', 'Giấu hộp bút rồi bỏ học.'],
  ['Nói: “Mình vui vì được chơi và buồn vì bạn về sớm.”', 'Giấu nỗi buồn vì chỉ được phép vui.', 'Nghĩ mình sai vì có hai cảm xúc.', 'Trách bạn vì đã làm mình buồn.'],
  ['Đặt đồ xuống, nghỉ ở chỗ an toàn rồi nói mình đang giận.', 'Hét vào mặt em ngay.', 'Đập đồ để hết giận.', 'Đẩy em ra để lấy lại đồ.'],
  ['Nam chờ Lan kể xong rồi mới nói chuyện của mình.', 'Nam chen vào để kể nhanh hơn.', 'Nam bỏ đi khi Lan còn đang kể.', 'Nam nói Lan không được kể nữa.'],
  ['Xin lỗi vì làm rách tranh và hỏi có thể giúp dán lại không.', 'Chạy đi vì đã nói xin lỗi rồi.', 'Đổ lỗi cho bạn để tránh bị trách.', 'Bảo bạn không được buồn nữa.'],
  ['Nói: “Mẹ ơi, mẹ chuyền giúp con bình nước nhé.”', 'Tiếp tục hét “Nước!” thật to.', 'Giật bình nước từ tay mẹ.', 'Giận vì mẹ chưa hiểu ngay.'],
  ['Nhặt bút, xin lỗi bạn, lắng nghe và nhờ cô khi cần.', 'Bỏ mặc bút rồi trách bạn.', 'Chen ngang bạn để hỏi cô ngay.', 'Giấu việc làm rơi bút và bỏ qua bài chưa hiểu.'],
  ['Tối trước, xem thời khóa biểu và kiểm tra đồ trong cặp.', 'Đợi sát giờ đi học mới tìm vở.', 'Mang tất cả đồ trong nhà vào cặp.', 'Nhờ bố mẹ làm hết mà không cùng kiểm tra.'],
  ['Gom bút vào hộp và cất sách ở chỗ dễ lấy.', 'Để đồ ở đâu cũng được.', 'Giấu bút dưới ghế để khỏi mất.', 'Mỗi lần dùng xong lại đổi chỗ cất.'],
  ['Cùng người lớn xếp việc cần làm và dành thời gian nghỉ, chơi.', 'Chơi đến tối rồi mới tính.', 'Làm mọi việc cùng lúc.', 'Bỏ nghỉ ngơi để làm nhanh hơn.'],
  ['Nói: “Mình thử từng bước hoặc nhờ hướng dẫn nhé.”', 'Nói Linh chẳng làm được gì.', 'Bắt Linh làm đúng ngay lần sau.', 'Vò giấy và không bao giờ thử nữa.'],
  ['Chọn bút để đi học; đồ chơi có thể chờ.', 'Chọn đồ chơi dù không còn bút học.', 'Lấy cả hai món mà không hỏi.', 'Mua món có hộp đẹp hơn, không nghĩ đến nhu cầu.'],
  ['Hỏi người lớn và nhận việc vừa sức như xếp khăn.', 'Tự dùng hóa chất để lau bếp.', 'Tự mang nồi nóng đi rửa.', 'Không hỏi và dùng dao để giúp nhanh.'],
  ['Kiểm tra cặp, chuẩn bị áo từ tối và vẫn dành giờ ăn sáng.', 'Bỏ bữa sáng để kịp giờ.', 'Đợi lúc ra cửa mới kiểm tra cặp.', 'Làm mọi việc thật vội mà không nhờ giúp.'],
  ['Hỏi: “Mình chơi cùng được không?” và tôn trọng câu trả lời.', 'Giành đồ chơi để được tham gia.', 'Ép các bạn phải cho mình chơi ngay.', 'Phá trò chơi vì chưa được mời.'],
  ['Thỏa thuận chia màu hoặc lần lượt dùng hộp màu.', 'Kéo hộp màu thật mạnh về mình.', 'Giấu hộp để bạn không được dùng.', 'Giữ hết màu vì mình thích hơn.'],
  ['Nghe ý bạn rồi đề nghị chia giấy hoặc vẽ biển và rừng cùng nhau.', 'Ép bạn vẽ đúng ý mình.', 'Xé giấy để khỏi phải chọn.', 'Chê ý tưởng của bạn.'],
  ['Đến nơi có người lớn tin cậy và kể rõ chuyện bị trêu.', 'Chịu đựng và không kể với ai.', 'Đánh bạn để bạn sợ.', 'Tin rằng mình có lỗi vì bị trêu.'],
  ['Hỏi bạn mới thích gì và muốn tham gia thế nào.', 'Trêu giọng nói của bạn.', 'Ép bạn chơi giống tất cả mọi người.', 'Không cho bạn tham gia vì bạn khác mình.'],
  ['Liệt kê việc rồi thống nhất ai gấp giấy, viết và tô màu.', 'Ai cũng tô màu, bỏ các việc khác.', 'Giành phần mình thích.', 'Để một người làm hết tấm thiệp.'],
  ['Mời bạn mới, nghe từng ý và thống nhất cách chia lượt.', 'Không cho bạn mới chơi.', 'Người nói to nhất quyết định mọi việc.', 'Giành bộ đồ chơi về mình.'],
  ['Kể với người lớn biết lắng nghe; tìm người khác nếu chưa được giúp.', 'Giữ mọi lo lắng một mình.', 'Kể thông tin riêng cho bất kỳ ai trên mạng.', 'Bỏ cuộc nếu người đầu tiên chưa giúp được.'],
  ['Dừng ở khu vực an toàn và nhờ nhân viên tại quầy liên hệ gia đình.', 'Chạy ra ngoài siêu thị tìm bố mẹ.', 'Theo người lạ đến chỗ vắng.', 'Đi khắp nơi mà không nhờ hỗ trợ.'],
  ['Nói không muốn ôm và chọn chào bằng lời hoặc vẫy tay.', 'Cố chịu vì không được từ chối người quen.', 'Để người khác quyết định mọi tiếp xúc.', 'Nghĩ từ chối ôm là làm điều sai.'],
  ['Kể với người lớn tin cậy về điều khiến mình sợ.', 'Giữ kín vì đã bị dặn như vậy.', 'Tự chịu đựng để không ai biết.', 'Tin lời đe dọa rằng kể ra là có lỗi.'],
  ['Dừng trả lời, không gửi thông tin riêng và nhờ phụ huynh kiểm tra.', 'Gửi địa chỉ để nhận quà.', 'Gửi ảnh và tên trường vì đang cùng chơi.', 'Gửi thông tin rồi mới hỏi bố mẹ.'],
  ['Tránh xa dây điện và vũng nước, báo người lớn từ chỗ an toàn.', 'Chạm dây để xem có điện không.', 'Tự sửa dây điện.', 'Bước qua vũng nước để nhìn gần hơn.'],
  ['Ưu tiên chỗ an toàn và tìm người lớn có trách nhiệm giúp.', 'Tự xử lý mọi nguy hiểm để chứng tỏ mình giỏi.', 'Theo lời mời đi riêng mà không hỏi.', 'Đến gần vật nguy hiểm để xem thử.'],
  ['Nói thật việc quên tưới cây và cùng chọn cách nhắc cho lần sau.', 'Giấu chuyện quên tưới cây.', 'Đổ lỗi cho người khác.', 'Hứa thêm thật nhiều việc để bù lại.'],
  ['Kể một việc đã tiến bộ và chọn kỹ năng muốn luyện thêm.', 'So số bài học với bạn để xem ai giỏi hơn.', 'Bỏ kỹ năng còn khó vì mình chưa làm được.', 'Nghĩ học lại là thất bại.'],
];

// Each set addresses one skill across its five situations. Avoid generic
// distractors shared by unrelated topics: every option tests the lesson's idea.
export const skillChoices: Record<string, ChoiceSet> = {
  'chào hỏi phù hợp với người và hoàn cảnh': ['Chào nhẹ nhàng, chọn lời và cách chào hợp với người gặp.', 'Hét lời chào dù người khác cần yên tĩnh.', 'Chỉ chào khi được cho quà.', 'Bắt người khác phải ôm mình khi chào.'],
  'kể một việc theo trình tự dễ hiểu': ['Kể việc bắt đầu, diễn ra rồi kết thúc; nói rõ người và việc.', 'Đổi qua lại các đoạn khiến người nghe khó hiểu.', 'Chỉ nói đoạn cuối mà không giải thích.', 'Thêm việc chưa xảy ra để chuyện hay hơn.'],
  'đặt câu hỏi để hiểu rõ điều chưa biết': ['Hỏi rõ điều chưa hiểu và nghe câu trả lời.', 'Đoán ý rồi làm dù chưa rõ.', 'Im lặng vì hỏi lại là đáng xấu hổ.', 'Nói mình hiểu hết để khỏi phải hỏi.'],
  'nói ý kiến khác một cách tôn trọng': ['Nói ý của mình và lý do, rồi nghe ý của người khác.', 'Chê người có ý kiến khác.', 'Quát để mọi người đồng ý với mình.', 'Không cho người khác nêu lý do.'],
  'góp ý vào hành động cụ thể thay vì chê con người': ['Nói việc cần sửa và đề nghị cụ thể, bằng lời nhẹ nhàng.', 'Đặt biệt danh để bạn nhớ lỗi.', 'Nói bạn lúc nào cũng làm sai.', 'Chê bạn trước mọi người.'],
  'đón nhận góp ý và hỏi cách cải thiện': ['Nghe điều cần sửa, hỏi nếu chưa rõ rồi thử sửa một bước.', 'Cãi ngay vì mọi góp ý đều sai.', 'Bỏ toàn bộ việc đang làm vì một lỗi nhỏ.', 'Nghĩ bị góp ý có nghĩa mình không có điểm tốt.'],
  'trình bày ngắn gọn trước một nhóm nhỏ': ['Chọn ý chính, nói chậm và nhờ giúp nếu quên.', 'Nói thật nhanh để xong ngay.', 'Kể mọi chuyện không liên quan.', 'Không cho nhóm hỏi điều chưa rõ.'],
  'nói lời cảm ơn cụ thể và chân thành': ['Cảm ơn và nói rõ việc người kia đã giúp mình.', 'Chỉ cảm ơn khi nhận quà lớn.', 'Coi việc người khác giúp mình là bắt buộc.', 'Đòi người khác phải giúp thêm mới cảm ơn.'],
  'trao đổi tin nhắn ngắn rõ ràng với người quen dưới sự hướng dẫn': ['Cùng người lớn kiểm tra người nhận và gửi lời nhắn rõ, lịch sự.', 'Gửi liên tục dù chưa cần.', 'Tự gửi thông tin riêng cho tài khoản chưa rõ.', 'Chỉ gửi một từ khiến người nhận phải đoán.'],
  'xin phép và báo lại khi dùng đồ hoặc thay đổi kế hoạch': ['Hỏi người phụ trách trước, rồi báo lại khi có thay đổi.', 'Dùng đồ trước rồi hỏi sau.', 'Thay đổi kế hoạch mà không báo ai.', 'Nghĩ người khác tự biết mình định làm gì.'],
  'nhận ra dấu hiệu cảm xúc trong cơ thể': ['Chú ý dấu hiệu cơ thể và thử gọi tên cảm xúc của mình.', 'Bỏ qua mọi dấu hiệu cơ thể.', 'Nghĩ tim đập nhanh luôn có cùng một lý do.', 'Tự trách mình vì cảm thấy lo hoặc giận.'],
  'tạo khoảng nghỉ để lấy lại bình tĩnh': ['Tạm dừng ở chỗ an toàn, thở chậm rồi nói điều mình cần.', 'Tiếp tục cãi khi đang rất giận.', 'Đập đồ để cảm xúc biến mất.', 'Bỏ đi xa mà không báo người lớn.'],
  'ứng xử khi thất vọng mà không tự chê mình': ['Nói mình thất vọng, nghỉ một chút rồi tìm bước tiếp theo.', 'Nói mình chẳng bao giờ làm được gì.', 'Đổ lỗi cho mọi người vì mình thất vọng.', 'Bắt mình phải làm hoàn hảo ngay.'],
  'chăm sóc nỗi buồn và tìm người lắng nghe': ['Cho mình thời gian và tìm người tin cậy để chia sẻ nếu muốn.', 'Giấu nỗi buồn vì buồn là sai.', 'Ép mình phải vui ngay.', 'Nghĩ không ai được biết mình buồn.'],
  'nhận ra ghen tị và chuyển thành mong muốn có thể nói': ['Nhận ra mình ghen tị và nói điều mình mong muốn.', 'Chê điều tốt của người khác.', 'Giành món đồ mình đang thích.', 'Tự trách vì có cảm xúc ghen tị.'],
  'giảm lo lắng bằng việc phân biệt điều biết và điều đang đoán': ['Tách điều biết rõ khỏi điều đang đoán và hỏi người tin cậy.', 'Coi điều lo nhất chắc chắn sẽ xảy ra.', 'Tự đoán thêm mà không kiểm tra.', 'Giấu lo lắng vì không được nhờ giúp.'],
  'tự nói với mình bằng lời tử tế': ['Nhắc mình đang học và có thể thử từng bước.', 'Nói mình vô dụng vì mắc một lỗi.', 'So mình với người giỏi nhất để tự trách.', 'Bắt mình không được sai lần nào.'],
  'kiên trì bằng cách thay đổi chiến lược và nghỉ đúng lúc': ['Thử cách khác, chia bước hoặc nghỉ và nhờ hướng dẫn.', 'Lặp lại cách chưa hiệu quả mãi.', 'Không nghỉ dù đã quá mệt.', 'Bỏ luôn vì lần đầu chưa thành công.'],
  'tự tin từ những điểm mạnh và tiến bộ cụ thể': ['Nhớ một việc mình đã làm tốt và chọn bước nhỏ để thử.', 'Nghĩ chỉ người đứng nhất mới có điểm mạnh.', 'Chê bạn để thấy mình giỏi hơn.', 'Phải làm được mọi thứ mới dám thử.'],
  'chấp nhận sai sót và rút ra điều học được': ['Nhận lỗi, sửa điều có thể sửa và nhớ cách làm cho lần sau.', 'Giấu lỗi để không phải sửa.', 'Đổ lỗi cho người bên cạnh.', 'Nghĩ một lỗi làm mình kém mãi mãi.'],
  'chuyển hoạt động bằng lời báo và bước kết thúc nhỏ': ['Nghe lời báo, kết thúc một bước nhỏ rồi chuyển việc theo thỏa thuận.', 'Bỏ mọi đồ đang dùng ngổn ngang.', 'Cố kéo dài dù đã thống nhất giờ dừng.', 'Quát người nhắc mình chuyển việc.'],
  'nhận ra niềm vui nhỏ mà không phủ nhận cảm xúc khó': ['Nhớ điều vui nhỏ và vẫn cho phép mình nói điều buồn hoặc khó.', 'Nghĩ có điều vui thì không được buồn.', 'Ép người khác phải vui giống mình.', 'Bỏ qua mọi điều tốt vì hôm nay có việc khó.'],
  'lập danh sách kiểm tra ngắn cho việc thường ngày': ['Liệt kê vài món cần thiết và kiểm tra từng món.', 'Chỉ nhớ trong đầu dù thường hay quên.', 'Ghi quá nhiều việc không cần thiết.', 'Đánh dấu đã xong dù chưa kiểm tra.'],
  'sắp xếp góc học theo nhu cầu sử dụng': ['Để đồ hay dùng dễ lấy, gom đồ cùng loại và giữ lối đi gọn.', 'Để mọi thứ chồng lên nhau.', 'Cất đồ thường dùng ở chỗ rất khó lấy.', 'Chuyển đồ liên tục mà không có chỗ cố định.'],
  'chăm sóc đồ dùng cá nhân và báo khi hỏng': ['Dùng nhẹ nhàng, cất đúng chỗ và báo người lớn khi đồ hỏng.', 'Giấu đồ hỏng để khỏi bị hỏi.', 'Tự tháo sửa mọi đồ dùng.', 'Tiếp tục dùng dù thấy có nguy cơ.'],
  'tự chọn trang phục phù hợp với hoạt động và thời tiết': ['Xem hoạt động và thời tiết rồi chọn đồ vừa vặn, hỏi nếu chưa rõ.', 'Chỉ chọn đồ đẹp dù không phù hợp hoạt động.', 'Mặc đồ gây khó chịu mà không nói.', 'Bỏ qua thời tiết vì hôm nào cũng mặc giống nhau.'],
  'giữ vệ sinh tay trong những sinh hoạt quen thuộc': ['Rửa tay đúng cách khi cần, nhờ người lớn hướng dẫn nếu chưa rõ.', 'Chỉ rửa khi thấy bẩn rõ ràng.', 'Lau qua áo rồi coi như đã sạch.', 'Bỏ rửa tay để tiết kiệm thời gian.'],
  'chủ động nói nhu cầu ăn uống và chăm sóc cơ thể': ['Nói rõ khi đói, khát, đau hoặc mệt để được chăm sóc phù hợp.', 'Giấu đau hoặc mệt để cố làm tiếp.', 'Bỏ ăn uống vì đang bận.', 'Tự dùng thuốc mà không hỏi người lớn.'],
  'chuẩn bị khoảng nghỉ và giờ ngủ cùng gia đình': ['Cùng gia đình chuẩn bị chỗ nghỉ và giảm hoạt động trước giờ ngủ.', 'Cố thức dù cơ thể rất mệt.', 'Chơi màn hình mãi để dễ ngủ.', 'Giấu việc khó ngủ vì không muốn nhờ giúp.'],
  'chia nhiệm vụ dài thành những bước có thể bắt đầu': ['Chia việc thành bước nhỏ và bắt đầu từ một bước vừa sức.', 'Làm mọi phần cùng lúc.', 'Đợi đến lúc hết giờ mới bắt đầu.', 'Bỏ việc vì nhìn thấy quá nhiều phần.'],
  'ước lượng thời gian và điều chỉnh kế hoạch vừa sức': ['Ước lượng từng việc, chừa giờ nghỉ và điều chỉnh khi cần.', 'Xếp kín mọi phút, không nghỉ.', 'Cố làm thật nhanh dù không an toàn.', 'Không đổi kế hoạch dù biết thiếu thời gian.'],
  'tập trung bằng cách giảm điều gây xao nhãng': ['Cất thứ gây xao nhãng, chọn một việc và nghỉ khi cần.', 'Vừa làm vừa xem nhiều nội dung khác.', 'Để mọi đồ chơi ngay trước mặt khi cần tập trung.', 'Bắt mình tập trung liên tục dù quá mệt.'],
  'tự đánh giá việc đã làm bằng tiêu chí đơn giản': ['Kiểm tra theo vài điều rõ ràng rồi sửa một phần còn thiếu.', 'Chỉ nhìn nhanh và nói đã xong.', 'So với bạn thay vì xem việc mình cần làm.', 'Bỏ cả việc chỉ vì còn một chỗ cần sửa.'],
  'tìm cách xử lý khi thiếu đồ hoặc kế hoạch bị gián đoạn': ['Xem còn gì dùng được, hỏi cách thay thế an toàn và nhờ giúp.', 'Lấy đồ của người khác mà không hỏi.', 'Giấu việc thiếu đồ rồi không làm gì.', 'Tự thử cách có nguy cơ để làm cho xong.'],
  'mời bạn tham gia mà tôn trọng quyền lựa chọn': ['Mời thân thiện, hỏi bạn muốn tham gia không và tôn trọng câu trả lời.', 'Ép bạn chơi dù bạn không muốn.', 'Giận vì bạn chọn việc khác.', 'Không cho bạn chọn vai trong trò chơi.'],
  'tôn trọng đồ dùng và không gian riêng của bạn': ['Xin phép trước khi dùng hoặc xem, trả lại và tôn trọng lời từ chối.', 'Tự lấy vì là bạn thân.', 'Xem đồ riêng khi bạn không biết.', 'Giữ đồ mượn mãi vì mình thích.'],
  'chia việc theo khả năng và cùng theo dõi phần chung': ['Thống nhất phần việc vừa sức và báo khi cần hỗ trợ.', 'Để một bạn làm tất cả.', 'Chỉ làm phần mình thích dù chưa thống nhất.', 'Giấu việc chưa xong khiến nhóm không biết.'],
  'giải quyết bất đồng nhỏ bằng nhu cầu và phương án': ['Nói điều mình cần, nghe bạn và cùng chọn phương án công bằng.', 'Quát đến khi bạn nhường.', 'Bỏ qua hoàn toàn điều bạn muốn.', 'Phá đồ vì chưa thống nhất được.'],
  'chơi công bằng khi thắng, thua hoặc chưa rõ kết quả': ['Theo luật đã thống nhất, tôn trọng kết quả và hỏi lại khi chưa rõ.', 'Đổi luật để mình luôn thắng.', 'Chê người thua.', 'Giấu kết quả không có lợi cho mình.'],
  'hỗ trợ bạn buồn mà không ép kể hay hứa giữ chuyện nguy hiểm': ['Hỏi bạn cần gì, lắng nghe nếu bạn muốn và tìm người lớn khi cần bảo vệ.', 'Ép bạn kể trước cả nhóm.', 'Hứa giấu mọi chuyện kể cả khi bạn gặp nguy hiểm.', 'Đoán cảm xúc của bạn rồi quyết định thay.'],
  'tôn trọng khác biệt về khả năng và cách tham gia': ['Hỏi nhu cầu và cùng điều chỉnh để bạn có cách tham gia phù hợp.', 'Bắt bạn làm giống tất cả mọi người.', 'Bắt chước giọng nói để trêu bạn.', 'Không cho bạn tham gia vì bạn làm khác mình.'],
  'từ chối sức ép của bạn và chọn hành động phù hợp': ['Nói không với việc gây hại, chọn việc an toàn và tìm hỗ trợ nếu bị ép.', 'Làm theo mọi lời rủ để giữ tình bạn.', 'Giấu người lớn việc khiến mình lo.', 'Nghĩ phải chứng tỏ can đảm bằng việc nguy hiểm.'],
  'lên tiếng và tìm hỗ trợ khi thấy bạn bị đối xử không tốt': ['Không hùa theo; từ chỗ an toàn, báo người lớn để giúp bạn.', 'Cười theo để không bị nhóm chê.', 'Chia sẻ lời làm nhục bạn.', 'Lao vào đánh nhau để giải quyết.'],
  'giữ tình bạn qua những thay đổi mà không kiểm soát bạn': ['Nói lời quan tâm, hẹn khi phù hợp và tôn trọng thời gian riêng của bạn.', 'Bắt bạn chỉ chơi với mình.', 'Kiểm tra bạn liên tục.', 'Giận mỗi khi bạn có thêm bạn mới.'],
  'đi bộ cùng người lớn và dừng ở nơi sang đường phù hợp': ['Đi cùng người lớn, dừng và sang đường theo hướng dẫn an toàn.', 'Chạy theo đồ rơi ra đường.', 'Tự sang đường khi thấy người quen gọi.', 'Đi khỏi người lớn để đến nhanh hơn.'],
  'chuẩn bị an toàn trước khi đạp xe hoặc vận động có bánh': ['Nhờ người lớn kiểm tra bảo hộ, phương tiện và nơi chơi trước khi đi.', 'Bỏ mũ bảo hộ vì chỉ chơi một chút.', 'Chơi ở nơi có xe qua lại.', 'Tiếp tục đi khi đồ dùng có dấu hiệu hỏng.'],
  'giữ khoảng cách với nước và gọi trợ giúp thay vì tự cứu': ['Giữ chỗ an toàn, chỉ gần nước khi được giám sát và gọi người lớn nếu cần cứu giúp.', 'Tự xuống nước lấy đồ rơi.', 'Nhảy xuống cứu người dù chưa có người lớn.', 'Nghĩ biết bơi thì không cần giám sát.'],
  'nhận biết nguy cơ cháy và làm theo kế hoạch thoát an toàn': ['Báo người lớn, làm theo kế hoạch đến chỗ an toàn và không quay lại lấy đồ.', 'Trốn để không ai biết mình ở đâu.', 'Quay lại lấy món đồ yêu thích.', 'Tự thử lửa để xem có nguy hiểm không.'],
  'tránh thiết bị điện có dấu hiệu bất thường và báo người lớn': ['Giữ khoảng cách với thiết bị bất thường và báo người lớn.', 'Tự tháo thiết bị để sửa.', 'Chạm dây để xem còn điện không.', 'Thử dùng tiếp ở chỗ gần nước.'],
  'nhận ra đồ vật cần người lớn xử lý trong nhà': ['Không tự dùng đồ có nguy cơ hoặc chưa rõ công dụng; nhờ người lớn xử lý.', 'Nếm hoặc ngửi chất lạ để đoán.', 'Tự dùng thuốc thấy trong nhà.', 'Chạm đồ nóng để kiểm tra.'],
  'nói ranh giới cơ thể và kể điều làm con không thoải mái': ['Nói điều mình không muốn, đến chỗ an toàn và kể với người lớn tin cậy.', 'Chịu tiếp xúc dù không thoải mái.', 'Giữ kín mọi chuyện vì người kia yêu cầu.', 'Tự nhận lỗi khi người khác không tôn trọng ranh giới.'],
  'giữ an toàn khi tách khỏi người đi cùng': ['Dừng ở khu vực an toàn và nhờ người có trách nhiệm tại chỗ liên hệ gia đình.', 'Chạy đi tìm ở nhiều nơi.', 'Theo người mời đến chỗ vắng.', 'Giấu việc bị lạc vì sợ bị trách.'],
  'bảo vệ thông tin cá nhân và tài khoản khi dùng mạng': ['Giữ thông tin riêng và nhờ phụ huynh kiểm tra trước khi gửi hoặc kết bạn.', 'Gửi mã xác nhận cho người xin giúp.', 'Cho bạn trên mạng mật khẩu để nhận quà.', 'Gửi ảnh riêng vì người kia nói là quen mình.'],
  'dừng tương tác và nhờ hỗ trợ khi gặp nội dung gây hại trên mạng': ['Dừng xem, không đáp trả hoặc gửi tiếp và nhờ phụ huynh hỗ trợ.', 'Đáp trả lời đe dọa bằng lời xúc phạm.', 'Chia sẻ nội dung làm nhục người khác.', 'Làm thử thách nguy hiểm để được khen.'],
  'dùng thiết bị theo thỏa thuận và xin phép trước thao tác mới': ['Theo thỏa thuận, hỏi trước thao tác mới và báo ngay nếu bấm nhầm.', 'Tự cài hoặc mua mọi thứ mình thích.', 'Giấu lỗi thao tác để khỏi bị hỏi.', 'Bấm liên kết lạ trước rồi mới kiểm tra.'],
  'báo sự việc cần giúp bằng thông tin ngắn và rõ': ['Từ chỗ an toàn, nói ở đâu, chuyện gì và ai cần giúp; không biết thì nói không biết.', 'Đoán thêm chi tiết để kể cho đủ.', 'Quay vào chỗ nguy hiểm để kiểm tra.', 'Chỉ hét mà không nói nơi hoặc việc.'],
  'giữ an toàn khi di chuyển cùng gia đình hoặc nhà trường': ['Ở gần người phụ trách, xác nhận người đón và lên xuống theo hướng dẫn.', 'Tự rời nhóm khi thấy người quen.', 'Mở cửa khi phương tiện chưa dừng.', 'Bỏ thiết bị bảo vệ vì thấy bất tiện.'],
  'nói thật về điều mình làm và phân biệt sự thật với suy đoán': ['Kể đúng điều biết và đã làm; nói rõ phần mình chưa chắc.', 'Thêm chi tiết đang đoán như thể đó là sự thật.', 'Đổ lỗi để giấu phần mình làm.', 'Nói điều người khác muốn nghe dù không đúng.'],
  'giữ cam kết vừa sức và báo sớm khi cần thay đổi': ['Nhận việc vừa sức, chọn cách nhớ và báo sớm nếu cần đổi.', 'Hứa mọi việc dù biết không làm được.', 'Giấu việc mình chưa hoàn thành.', 'Cố làm dù đau hoặc không an toàn.'],
  'lập kế hoạch dùng một khoản nhỏ với phụ huynh': ['Cùng phụ huynh xem khoản được dùng và cân nhắc trước khi mua.', 'Mua ngay mà không xem mình có bao nhiêu.', 'Tự vay để mua thêm.', 'Tự mua trên mạng mà không hỏi.'],
  'cân nhắc nhu cầu trước quảng cáo và lời mời mua': ['Hỏi có cần không, đã có chưa và nhờ phụ huynh kiểm tra trước khi chọn.', 'Mua chỉ vì có quà tặng.', 'Tin mọi lời quảng cáo.', 'Mua ngay vì sợ phải chờ.'],
  'dùng nước và vật dụng chung có chừng mực': ['Dùng vừa đủ, tránh lãng phí và báo người lớn khi thấy hỏng hoặc rò rỉ.', 'Lấy thật nhiều đồ chung dù không cần.', 'Bỏ uống nước để tiết kiệm.', 'Tự tháo ống nước để sửa.'],
  'giảm rác và phân loại theo hướng dẫn tại nơi sinh hoạt': ['Dùng lại đồ sạch còn tốt, bỏ đúng nơi và để người lớn xử lý rác có nguy cơ.', 'Bỏ tất cả rác cùng một chỗ dù đã có hướng dẫn.', 'Tự nhặt vật sắc để dọn nhanh.', 'Vứt đồ còn dùng được vì không thích nữa.'],
  'chăm sóc không gian chung và sinh vật với sự hướng dẫn': ['Làm việc vừa sức, nhẹ nhàng và hỏi người phụ trách trước khi chăm sóc.', 'Tự cho vật nuôi ăn món chưa biết phù hợp không.', 'Chạm con vật không quen ngay.', 'Làm thật nhiều dù chưa được hướng dẫn.'],
  'ra quyết định bằng lựa chọn và ảnh hưởng tới người khác': ['Xem các lựa chọn, nghĩ ảnh hưởng và nhờ người lớn khi việc có rủi ro.', 'Chỉ nghĩ điều mình thích.', 'Không hỏi nhu cầu của người cùng tham gia.', 'Không đổi ý dù biết thêm điều quan trọng.'],
  'kiểm tra thông tin trước khi tin hoặc kể tiếp': ['Kiểm tra nguồn, nói chưa biết khi chưa rõ và nhờ phụ huynh xác minh.', 'Tin vì nhiều người đã kể.', 'Kể tiếp điều chưa kiểm tra như sự thật.', 'Làm theo mẹo lạ vì trông rất dễ.'],
  'nhìn lại tiến bộ và chọn điều muốn tiếp tục luyện': ['Nhớ một việc đã thử, ghi nhận tiến bộ và chọn mục tiêu nhỏ tiếp theo.', 'So số bài với bạn để quyết định ai giỏi hơn.', 'Không học lại vì như vậy là thất bại.', 'Chọn thật nhiều mục tiêu dù quá sức.'],
};
